version: '3'
services: 
  # MIGRATION CONTAINER (EXECUTES MIGRATION TO SQL SERVER)
  flyway:
    image: boxfuse/flyway
    command: >
      -url=jdbc:sqlserver://${SQL_SERVER}:${SQL_SERVER_PORT};databaseName='${SQL_TARGET_DB}'
      -user='${SQL_SERVER_USER}'
      -password=${SQL_SERVER_PASS}
      -connectRetries=60
      migrate
    volumes:
      - ./migrations:/flyway/sql

# Execute Example
# SQL_TARGET_DB=mydb SQL_SERVER=localhost SQL_SERVER_PORT=1433 SQL_SERVER_USER=admin SQL_SERVER_PASS=mypassword docker-compose -f "db\docker-compose.migration.yml" up --build

